### ISSUE TITLE
Panic in ubbagent

### ISSUE THREAD

**Issue by vkamra** [GoogleCloudPlatform/ubbagent#55]
A customer marketplace deployment hit the following issue in ubbagent:

```
panic: RetryingSender.maybeSend: loading from retry queue: unexpected end of JSON input
goroutine 15 [running]:
vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders.(*RetryingSender).maybeSend(0xc0005806e0, 0xbf97a99c50737bd1, 0x24e27478, 0x48378c0)
	/vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders/retry.go:199 +0x7d8
vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders.(*RetryingSender).run(0xc0005806e0, 0xbf97a99c50737bd1, 0x24e27478, 0x48378c0)
	/vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders/retry.go:149 +0x6a
created by vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders.newRetryingSender
	/vendor/github.com/GoogleCloudPlatform/ubbagent/pipeline/senders/retry.go:88 +0x244
```

**Comment by vkamra** [comment]
This is the 0.0.1 release of ubbagent - commit ID `99237800501e7c11259adb9af2d05e7ebf3db305`

**Comment by vkamra** [comment]
The `servicecontrol.json` file in the `epqueue` directory is empty. Could this be related?

```
# ls -lt /var/datadir/ubbagent/epqueue
total 0
-rw-rw-r-- 1 root root 0 Mar 26 23:50 servicecontrol.json
```

**Comment by vkamra** [comment]
That indeed seemed to be the issue. We deleted the `epqueue` directory and restarted the agent which unblocked us.

Would like to understand the root cause though where we could be left with an empty file here?

cc @huyhg

**Comment by huyhg** [comment]
Thanks for the bug report. @vkamra, do you have a copy of the ubbagent configuration? Would like to see how the persistence layer is configured.

**Comment by huyhg** [comment]
Would also be useful if we have the full manifest of the pod that runs ubbagent binary--interested in understanding how the `/var/datadir/ubbagent/epqueue` volume is configured.

**Comment by vkamra** [comment]
> Thanks for the bug report. @vkamra, do you have a copy of the ubbagent configuration? Would like to see how the persistence layer is configured.

```
$ cat /var/ubbagent/config.yaml
metrics:
- name: node_time
  type: int
  passthrough: {}
  endpoints:
  - name: on_disk
endpoints:
- name: on_disk
  disk:
    reportDir: /var/reports/ubbagent/reports
    expireSeconds: 3600
```

**Comment by vkamra** [comment]
> Would also be useful if we have the full manifest of the pod that runs ubbagent binary--interested in understanding how the `/var/datadir/ubbagent/epqueue` volume is configured.

```
$ kubectl get pod metering-svc-6d4cdd4c58-ss72s -oyaml
apiVersion: v1
kind: Pod
metadata:
  name: metering-svc-6d4cdd4c58-ss72s
spec:
  containers:
  - env:
    - name: AGENT_CONFIG_FILE
      value: /var/ubbagent/config.yaml
    - name: AGENT_STATE_DIR
      value: /var/reports/ubbagent
    - name: AGENT_CONSUMER_ID
      valueFrom:
        secretKeyRef:
          key: consumer-id
          name: reporting-secret
    - name: AGENT_REPORTING_KEY
      valueFrom:
        secretKeyRef:
          key: reporting-key
          name: reporting-secret
    image: <XXXX>
    name: metering-svc
    volumeMounts:
    - mountPath: /var/ubbagent
      name: meter-config
    - mountPath: /var/reports/
      name: metering-persistent-storage
  volumes:
  - name: metering-persistent-storage
    persistentVolumeClaim:
      claimName: metering-pv-claim
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metering-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ssd
  volumeMode: Filesystem
```

**Comment by vkamra** [comment]
@huyhg - I added the information you requested. I removed anything custom/internal from the Pod manifest.

**Comment by vkamra** [comment]
I am wondering if it's possible that the pod got rescheduled before the results from `WriteFile` in `disk.go` were flushed (https://github.com/GoogleCloudPlatform/ubbagent/blob/f8441fbc2a74bdf0580dd22ccc86d41438b10e74/persistence/disk.go#L83). That would leave a 0 length file behind which could trigger this.
